<?php

////// Web service error codes
define("WEBSERVICE_ERROR_SERVER_UNAVAILABLE", 1);

// Connection
define("WEBSERVICE_ERROR_LOGIN_FAILED", 2);
define("WEBSERVICE_ERROR_TOKEN_EXPIRED", 3);
define("WEBSERVICE_ERROR_INVALID_LOGIN", 4);
define("WEBSERVICE_ERROR_SYSTEM_DATE", 5);

define("WEBSERVICE_ERROR_INVALID_TOKEN", 6);
define("WEBSERVICE_ERROR_INVALID_USER", 7);
define("WEBSERVICE_ERROR_INVALID_OPERATION", 8);

define("WEBSERVICE_ERROR_MISSING_KEYS", 9);
define("WEBSERVICE_ERROR_MISSING_STATUS", 10);
define("WEBSERVICE_ERROR_MISSING_UPDATES", 11);
define("WEBSERVICE_ERROR_INVALID_KEYS", 12);
define("WEBSERVICE_ERROR_INVALID_STATUS", 13);
define("WEBSERVICE_ERROR_INVALID_UPDATES", 14);

define("WEBSERVICE_ERROR_QUERY_INSERT", 15);
define("WEBSERVICE_ERROR_QUERY_UPDATE", 16);
define("WEBSERVICE_ERROR_QUERY_DELETE", 17);

// Publications
define("WEBSERVICE_ERROR_INVALID_PUBLICATION_ID", 18);
define("WEBSERVICE_ERROR_REQUEST_PUBLICATION_DELETE", 19);
define("WEBSERVICE_ERROR_REQUEST_PUBLICATION_INSERT", 20);

// Comments
define("WEBSERVICE_ERROR_REQUEST_COMMENT_DELETE", 21);
define("WEBSERVICE_ERROR_REQUEST_COMMENT_INSERT", 22);

?>
